---
title: "linearmodel"
author: "Jamie Santiago"
date: "Summer 2025"
output: html_document
---

```{r include=FALSE,echo=FALSE}
require(knitr)
require(tidyverse)
require(tigerstats)
data <- read.csv(file="https://onlinestatbook.com/case_studies_rvls/physical_strength/data.txt", sep="", header=TRUE)
```

```{r}
data <- read.csv(file="https://onlinestatbook.com/case_studies_rvls/physical_strength/data.txt",sep="",header=TRUE) 
```

```{r}
basicNN <- ggplot(data,aes(y=SIMS,x=ARM))
```

```{r}
basicNN + geom_point() + ggtitle("SIMS~ARM")+ theme(plot.title = element_text(hjust = 0.5, size = 20))
```

```{r}
cor(SIMS~ARM,data=data)
```

```{r}
model.1 <- lm(SIMS~ARM,data=data)
summary.lm(model.1)
```


```{r}
simp <- lm(SIMS~ARM,data=data)
plot(SIMS~ARM,data=data)
abline(simp)
summary.lm(simp)
```
```{r}
model.1 <- lm(SIMS~ARM,data=data)
summary.lm(model.1)
```

```{r}
ARMGRIP <- data.frame(ARM = 88,GRIP = 94)
```
 
```{r}
target<-data.frame(ARM=88, GRIP=94)
```

```{r}
predict(simp,target,interval=c("prediction"))
```

```{r}
predict(simp,target,interval=c("prediction"))
```

```{r}
newGRIP <- lm(SIMS~ARM,data=data)
plot(SIMS~ARM,data=data)
abline(simp)
summary.lm(simp)
```
```{r}
predict(newGRIP,target,interval=c("prediction"))
```

```{r}
ARMGRIP_2<- lm(SIMS~ARM+GRIP,data=data)
plot(SIMS~GRIP,data=data)
abline(ARMGRIP_2)
summary.lm(ARMGRIP_2)
```

```{r}
predict(ARMGRIP_2,target,interval=c("prediction"))
```